apiversion: 1

datasources:
  - name: PostgreSql
    type: grafana-postgresql-datasource
    typeName: PostgreSQL
    typeLogoUrl: public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg
    access: proxy
    url: db:5432
    isDefault: true
    editable: true
    user: 1
    password: 2
    database: iot
    basicAuth: false
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      sslmode: disable
      timescaledb: true
