name: iotbigdata

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile.production
      target: base
    volumes:
      - ../frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
    command: npm run dev
    env_file:
      - ../config/environment-variables/.env.frontend.prod
    networks:
      - internal

  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    expose:
      - "3001"
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/.env.backend.prod
    volumes:
      - ../backend/src:/usr/src/app/src
    configs:
      - source: backend_nodemon
        target: /usr/src/app/nodemon.json
    networks:
      - internal

  db:
    container_name: db
    image: timescale/timescaledb:latest-pg17
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 5432:5432
    env_file:
      - ../config/environment-variables/.env.db.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  grafana:
    container_name: grafana
    image: grafana/grafana:main
    ports:
      - 9200:9200
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/.env.grafana.prod
    volumes:
      - ../config/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ../config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../config/grafana/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ../config/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      - internal
      - public

  mqtt5:
    container_name: mqtt5
    build:
      context: ..
      dockerfile: docker/mosquitto.Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "9001:9001"
    env_file:
      - ../config/environment-variables/.env.mqtt.prod
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - mqtt-data:/mosquitto/data:rw
      - mqtt-log:/mosquitto/log:rw
    networks:
      - internal

  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 80:80
      - 1883:1883
    depends_on:
      - backend
      - mqtt5
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - internal
      - tunnel
      - public

  tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    command: tunnel run
    env_file:
      - ../config/environment-variables/.env.cloudflare.prod
    volumes:
      - cloudflare-tunnel:/etc/cloudflared
    networks:
      - public
      - tunnel

networks:
  public:
    driver: bridge
  tunnel:
    driver: bridge
    internal: true
  internal:
    driver: bridge
    internal: true

volumes:
  postgres_data: {}
  mqtt-data: {}
  mqtt-log: {}
  cloudflare-tunnel: {}
  grafana-data: {}

configs:
  nginx_config:
    file: ../config/nginx.conf
  backend_nodemon:
    file: ../backend/nodemon.json
