name: zero-prod

services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: ../frontend/
      dockerfile: Dockerfile
      target: base
    volumes:
      - ../frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "backend-prod"
    command: npm run dev
    env_file:
      - ../config/environment-variables/.env.frontend.prod
    networks:
      - internal-prod

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:main
  #   expose:
  #     - 9200:9200
  #   depends_on:
  #     - db
  #     # - clickhouse
  #   env_file:
  #     - ../config/environment-variables/.env.grafana.dev
  #   volumes:
  #     - ../config/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
  #     - ../config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  #     - ../config/grafana/main.yml:/etc/grafana/provisioning/dashboards/main.yml
  #     - ../config/grafana/dashboards/:/var/lib/grafana/dashboards/
  #     - grafana-data:/var/lib/grafana
  #   networks:
  #     - internal
  #     - public

  backend-prod:
    container_name: backend-prod
    build:
      context: ../backend/
      dockerfile: Dockerfile.production
      target: base
    expose:
      - "3001"
    command: ["npm", "run", "dev"]
    depends_on:
      - db-prod
    env_file:
      - ../config/environment-variables/.env.backend.prod
    volumes:
      - ../backend/src:/usr/src/app/src
    configs:
      - source: backend_nodemon
        target: /usr/src/app/nodemon.json
    networks:
      - internal-prod

  db-prod:
    container_name: db-prod
    image: timescale/timescaledb:latest-pg17
    expose:
      - "5432"
    ports:
      - 5432:5432
    env_file:
      - ../config/environment-variables/.env.db.prod
    volumes:
      - postgres_data-prod:/var/lib/postgresql/data
    networks:
      - public-prod
      - internal-prod

  mosquitto-prod:
    image: eclipse-mosquitto:latest
    hostname: mosquitto-prod
    container_name: mosquitto-prod
    restart: unless-stopped
    ports:
      - "1883:1883" # MQTT
      - "8080:8080" # MQTTS (secure)
      - "9001:9001" # WebSockets
    volumes:
      - mqtt-data-prod:/mosquitto/data
      - mqtt-log-prod:/mosquitto/log
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
    networks:
      - internal-prod
      - public-prod

  # clickhouse:
  #   container_name: clickhouse
  #   build:
  #     context: ..
  #     dockerfile: docker/clickhouse.Dockerfile
  #   ports:
  #     - 9000:9000
  #     - 8123:8123
  #   depends_on:
  #     - db
  #   env_file:
  #     - ../config/environment-variables/.env.clickhouse.dev
  #     - ../config/environment-variables/.env.db.dev
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #   networks:
  #     - public
  #     - internal

  reverse-proxy-prod:
    container_name: reverse-proxy-prod
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 443:443
      - 80:80
      # - 8080:8080
      # - 1883:1883
    depends_on:
      - backend-prod
      - mosquitto-prod

      # - grafana
      # - clickhouse
    env_file:
      - ../config/environment-variables/.env.nginx.prod
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_stream_config
        target: /etc/nginx/conf.d/01-mqtt.stream
    networks:
      - internal-prod
      - public-prod

networks:
  public-prod:
    driver: bridge
  internal-prod:
    name: internal-prod
    internal: true

volumes:
  postgres_data-prod: {}
  mqtt-data-prod: {}
  mqtt-log-prod: {}
  # grafana-data: {}
  # clickhouse_data: {}
  # cert-link: {}
  # cert: {}
  # cert-config: {}

configs:
  nginx_config:
    file: ../config/nginx.prod.conf
  nginx_stream_config:
    file: ../config/01-mqtt.prod.stream
  mosquitto_config:
    file: ../config/mosquitto.prod.conf
  backend_nodemon:
    file: ../backend/nodemon.json
