name: zero

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
      target: base
    volumes:
      - ../frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
    command: npm run dev
    env_file:
      - ../config/environment-variables/.env.frontend.dev
    networks:
      - internal

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:main
  #   expose:
  #     - 9200:9200
  #   depends_on:
  #     - db
  #     # - clickhouse
  #   env_file:
  #     - ../config/environment-variables/.env.grafana.dev
  #   volumes:
  #     - ../config/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
  #     - ../config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  #     - ../config/grafana/main.yml:/etc/grafana/provisioning/dashboards/main.yml
  #     - ../config/grafana/dashboards/:/var/lib/grafana/dashboards/
  #     - grafana-data:/var/lib/grafana
  #   networks:
  #     - internal
  #     - public

  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base
    expose:
      - "3001"
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/.env.backend.dev
    volumes:
      - ../backend/src:/usr/src/app/src
    configs:
      - source: backend_nodemon
        target: /usr/src/app/nodemon.json
    networks:
      - internal

  db:
    container_name: db
    image: timescale/timescaledb:latest-pg17
    expose:
      - "5432"
    ports:
      - 5432:5432
    env_file:
      - ../config/environment-variables/.env.db.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - public
      - internal

  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" # MQTT
      - "8080:8080" # MQTTS (secure)
      - "9001:9001" # WebSockets
    volumes:
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
    networks:
      - internal

  # clickhouse:
  #   container_name: clickhouse
  #   build:
  #     context: ..
  #     dockerfile: docker/clickhouse.Dockerfile
  #   ports:
  #     - 9000:9000
  #     - 8123:8123
  #   depends_on:
  #     - db
  #   env_file:
  #     - ../config/environment-variables/.env.clickhouse.dev
  #     - ../config/environment-variables/.env.db.dev
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #   networks:
  #     - public
  #     - internal

  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 443:443
      - 80:80
      - 8080:8080
      - 1883:1883
    depends_on:
      - backend
      # - grafana
      # - clickhouse
    env_file:
      - ../config/environment-variables/.env.nginx.dev
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_stream_config
        target: /etc/nginx/conf.d/01-mqtt.stream
    networks:
      - internal
      - public

networks:
  public:
    driver: bridge
  internal:
    name: internal
    internal: true

volumes:
  postgres_data: {}
  mqtt-data: {}
  mqtt-log: {}
  # grafana-data: {}
  # clickhouse_data: {}
  # cert-link: {}
  # cert: {}
  # cert-config: {}

configs:
  nginx_config:
    file: ../config/nginx.conf
  nginx_stream_config:
    file: ../config/01-mqtt.stream
  mosquitto_config:
    file: ../config/mosquitto.dev.conf
  backend_nodemon:
    file: ../backend/nodemon.json
